server:
  port: 80
eureka:
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.xbinx.springcloud.service.PaymentFeignService: debug
